Terraform 1
Otus-DevOps-2020-02/dkushner1974_infra pull request #6
Opened 2020-03-27 11:37 UTC by dkushner1974

# Выполнено ДЗ №4

 - [ ] Основное ДЗ
создание и проверка интеграции с travis
 - [ ] Задание со *

## В процессе сделано:
 - Интеграция со Slack
 - Интеграция и проверка Travis

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2020-03-28 11:55 UTC, mrgreyves requested changes
Здравствуйте!) Првоерил ваше дз. Нужно поправить тесты. Оставил комментарий к файлу.

2020-03-28 11:55 UTC, mrgreyves commented on terraform/main.tf
> +  required_version = "0.12.24"
Попробуйте указать версию ~> 0.12.12

2020-03-30 06:22 UTC, dkushner1974 commented
Доброе утро!
 
не помогло
  
>Суббота, 28 марта 2020, 14:55 +03:00 от Vladimir Drozdetskiy <notifications@github.com>:
> 
> 
>@mrgreyves requested changes on this pull request.
>Здравствуйте!) Првоерил ваше дз. Нужно поправить тесты. Оставил комментарий к файлу.
>----------------------------------------------------------------------
>In  terraform/main.tf :
>> @@ -0,0 +1,88 @@
>
>+terraform {
>
>+  # Версия terraform
>
>+  required_version = "0.12.24"
>
>
>Попробуйте указать версию ~> 0.12.12
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Dmitry Kushner
dyk@mail.ru
 

2020-03-30 09:22 UTC, mrgreyves requested changes
Здравствуйте!) Оставил комментарий к файлу.

2020-03-30 09:22 UTC, mrgreyves commented on terraform/main.tf
> +  required_version = "0.12.12"
Давайте попробуем указать не точное соответствие, а например вот это ~> 0.12

2020-03-30 09:36 UTC, dkushner1974 commented
та же ерунда

  
>Понедельник, 30 марта 2020, 12:23 +03:00 от Vladimir Drozdetskiy <notifications@github.com>:
> 
> 
>@mrgreyves requested changes on this pull request.
>Здравствуйте!) Оставил комментарий к файлу.
>----------------------------------------------------------------------
>In  terraform/main.tf :
>> @@ -0,0 +1,88 @@
>
>+terraform {
>
>+  # Версия terraform
>
>+  required_version = "0.12.12"
>
>
>Давайте попробуем указать не точное соответствие, а например вот это ~> 0.12
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Dmitry Kushner
dyk@mail.ru
 

2020-03-30 09:42 UTC, mrgreyves requested changes
Так вы же ничего не изменили. 
![image](https://user-images.githubusercontent.com/34331259/77898506-ec5cac00-7283-11ea-93fc-3b6b23269440.png)

2020-03-30 10:42 UTC, dkushner1974 commented
было 
"0.12.12" как надо то? в тесте что проверяется?

  
>Понедельник, 30 марта 2020, 12:42 +03:00 от Vladimir Drozdetskiy <notifications@github.com>:
> 
> 
>@mrgreyves requested changes on this pull request.
>Так вы же ничего не изменили.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
С уважением,
Dmitry Kushner
dyk@mail.ru
 

2020-04-13 11:01 UTC, merged